apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apps
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
      - name: apps
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apps
spec:
  selector:
    app: apps
  ports:
  - port: 80
    targetPort: 80
  type: NodePort  

